services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./rules.yml:/etc/prometheus/rules.yml
    command: >
      --config.file=/etc/prometheus/prometheus.yml
      --web.enable-remote-write-receiver
  grafana-latest:
    container_name: grafana-latest
    image: grafana/grafana:latest
    ports:
      - "4000:3000"
    restart: always
    volumes:
      - ./provisioning:/etc/grafana/provisioning
      - ./dashboards:/var/lib/grafana/dashboards
    environment:
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: "/var/lib/grafana/dashboards/system.json"
      GF_ADMIN_PASSWORD: "admin"
  loki:
    image: grafana/loki:2.9.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
  alertmanager:
    image: prom/alertmanager:latest
    restart: always
    ports:
      - "9093:9093"
    volumes:
      - "./alertmanager:/config"
      - alertmanager-data:/data
    # command: --config.file=/config/alertmanager.yml --log.level=debug

volumes:

  alertmanager-data: