- name: Copy Prometheus systemd unit file with remote write receiver enabled
  hosts: prometheus
  remote_user: ubuntu
  become: yes
  tasks:
    - name: Copy Prometheus systemd unit file template
      template:
        src: prometheus.service.j2
        dest: /etc/systemd/system/prometheus.service
      notify:
        - Restart Prometheus service

  handlers:
    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes
    - name: Restart Prometheus service
      systemd:
        name: prometheus
        state: restarted
