---
- name: Install Nginx & fluent-bit
  hosts: nodes
  remote_user: ubuntu
  gather_facts: yes
  become: yes
  vars:
    fluentbit_codename: "{{ ansible_distribution_release }}"
    hostname:  "{{inventory_hostname }}"
  roles:
  - nginx
  - fluent-bit
